docker_version:                       "17.12.1~ce-0~ubuntu"
docker_compose_version:               "1.19.0"
docker_apt_release_channel:           "stable"
docker_apt_repository:                "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

uninstall_previous_docker_versions:   false

docker_group_member:                  "{{ ansible_ssh_user if ansible_ssh_user is defined else USER }}"
