---

- name: "Uninstall old versions of Docker"
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "docker"
    - "docker-engine"
    - "docker.io"
  when: uninstall_previous_docker_versions

- name: "Install docker dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"

- name: "Add docker repo apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: "Add Docker repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    mode: '644'
    state: present
    update_cache: yes
